version: '3'
services:
  python_app:
    image: cynario-python
    container_name: cynario-python-cnt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - redis

  redis:
    image: redis:latest
    command: redis-server --appendonly yes --requirepass ""
    environment:
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis_exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - 9121:9121
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - python_app

volumes:
  redis-data:
