global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'python'
    metrics_path: /prom-metrics
    static_configs:
      - targets: ['python_app:5000']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
